INSERT INTO GUNS_TYPES VALUES ('Pistol');
INSERT INTO GUNS_TYPES VALUES ('Revolver');
INSERT INTO GUNS_TYPES VALUES ('Rifle');
INSERT INTO GUNS_TYPES VALUES ('Carbine');
INSERT INTO GUNS_TYPES VALUES ('Assault Rifle');
INSERT INTO GUNS_TYPES VALUES ('Machine Pistol');
INSERT INTO GUNS_TYPES VALUES ('Machine Gun');

INSERT INTO BULLETS_TYPES VALUES ('Armor-piercing');
INSERT INTO BULLETS_TYPES VALUES ('Ball');
INSERT INTO BULLETS_TYPES VALUES ('Tracer');
INSERT INTO BULLETS_TYPES VALUES ('Incendiary');

INSERT INTO GUNS VALUES
  (DEFAULT, random_uuid(), 'Assault Rifle', 'Ak-47', 10000, 'USSR', 'ak from ussr', 1000, 500, 30, '7.62x39mm', 600);
INSERT INTO GUNS VALUES
  (DEFAULT, random_uuid(), 'Pistol', 'five seven', 5000, 'USA', 'simple five seven', 200, 50, 20, '5.7x28mm', NULL);
INSERT INTO BULLETS VALUES (DEFAULT, random_uuid(), '7.62x39mm', 'BEAR BROWN', NULL, 140, 300, NULL);
INSERT INTO BULLETS VALUES (DEFAULT, random_uuid(), '7.62x39mm', 'BEAR SILVER', NULL, 160, 300, NULL);
INSERT INTO BULLETS VALUES (DEFAULT, random_uuid(), '5.7x28mm', 'Federal', NULL, 24, 500, NULL);
